# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Sep 20 21:24:06 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(400, 270)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Main)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lcdTimer = QtGui.QLCDNumber(Main)
        self.lcdTimer.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdTimer.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdTimer.setMidLineWidth(0)
        self.lcdTimer.setNumDigits(9)
        self.lcdTimer.setObjectName("lcdTimer")
        self.horizontalLayout_7.addWidget(self.lcdTimer)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnStartStop = QtGui.QPushButton(Main)
        self.btnStartStop.setAutoDefault(True)
        self.btnStartStop.setDefault(True)
        self.btnStartStop.setObjectName("btnStartStop")
        self.horizontalLayout_6.addWidget(self.btnStartStop)
        self.btnReset = QtGui.QPushButton(Main)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout_6.addWidget(self.btnReset)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblDedicatedTo = QtGui.QLabel(Main)
        self.lblDedicatedTo.setObjectName("lblDedicatedTo")
        self.verticalLayout_3.addWidget(self.lblDedicatedTo)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cboProjects = QtGui.QComboBox(Main)
        self.cboProjects.setObjectName("cboProjects")
        self.horizontalLayout_5.addWidget(self.cboProjects)
        self.btnManage = QtGui.QToolButton(Main)
        self.btnManage.setObjectName("btnManage")
        self.horizontalLayout_5.addWidget(self.btnManage)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btnSave = QtGui.QPushButton(Main)
        self.btnSave.setDefault(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnQuit = QtGui.QPushButton(Main)
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout_4.addWidget(self.btnQuit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)
        Main.setTabOrder(self.btnStartStop, self.cboProjects)
        Main.setTabOrder(self.cboProjects, self.btnSave)
        Main.setTabOrder(self.btnSave, self.btnQuit)
        Main.setTabOrder(self.btnQuit, self.btnReset)
        Main.setTabOrder(self.btnReset, self.btnManage)

    def retranslateUi(self, Main):
        Main.setWindowTitle(QtGui.QApplication.translate("Main", "MyWela", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartStop.setText(QtGui.QApplication.translate("Main", "S&tart", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("Main", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDedicatedTo.setText(QtGui.QApplication.translate("Main", "Dedicate to:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnManage.setText(QtGui.QApplication.translate("Main", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("Main", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQuit.setText(QtGui.QApplication.translate("Main", "&Quit", None, QtGui.QApplication.UnicodeUTF8))

